version: "3.9"

x-aliases:
  - &DEFAULT_ARGS
    DOCKER_VERSION: ${DOCKER_VERSION:-20.10.17}
    DOCKER_COMPOSE_VERSION: ${DOCKER_COMPOSE_VERSION:-1.29.0}
    DOCKER_BUILDX_VERSION: ${DOCKER_BUILDX_VERSION:-0.8.2}
    DOCKER_AWS_ECR_CREDENTIAL_HELPER_VERSION: ${DOCKER_AWS_ECR_CREDENTIAL_HELPER_VERSION:-0.5.0}
    DOCKER_PASS_CREDENTIAL_HELPER_VERSION: ${DOCKER_PASS_CREDENTIAL_HELPER_VERSION:-0.6.3}

volumes:
  dind-ca: {}
  dind-server: {}
  dind-client: {}

networks:
  dind: {}

services:
  local:
    image: ${REGISTRY:-docker.io}/${NAMESPACE:-openswoolebundle}/${PROJECT_NAME:-docker-client}-local:${IMAGE_TAG:-local}
    build:
      context: .
      target: "${TARGET:-client}"
      args:
        <<: *DEFAULT_ARGS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./examples:/workspace:ro

  dind:
    image: docker.io/docker:${DOCKER_VERSION:-20.10.17}-dind
    restart: always
    privileged: true
    environment:
      # same as docker-compose service
      DOCKER_TLS_SAN: DNS:dind
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - dind-ca:/certs/ca:rw
      - dind-server:/certs/server:rw
      - dind-client:/certs/client:rw
    networks:
      - dind

  remote:
    image: ${REGISTRY:-docker.io}/${NAMESPACE:-openswoolebundle}/${PROJECT_NAME:-docker-client}-remote:${IMAGE_TAG:-local}
    depends_on:
      - dind
    build:
      context: .
      target: "${TARGET:-client}"
      args:
        <<: *DEFAULT_ARGS
    environment:
      DOCKER_HOST: tcp://dind:2376
      DOCKER_TLS_CERTDIR: /certs
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
      DOCKER_BUILDX_CONTEXT_CREATE: 1
      DOCKER_BUILDX_BUILDER_CREATE: 1
    volumes:
      - dind-client:/certs/client:ro
      - ./examples:/workspace:ro
    networks:
      - dind

  example-nginx:
    image: ${REGISTRY:-docker.io}/${NAMESPACE:-openswoolebundle}/${PROJECT_NAME:-docker-client}-example-nginx:${IMAGE_TAG:-local}
    build:
      context: examples/nginx
